language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - 8.1
    - 'nightly'

env:
    global:
        - TEST_COMMAND="./vendor/bin/phpunit"
    matrix:
        - SUITE="Guzzle"
        - SUITE="Laminas"
        - SUITE="Slim"
        - SUITE="Nyholm"
        - SUITE="RingCentral"

branches:
    except:
        - /^analysis-.*$/
        - /^patch-.*$/

before_install:
    - iphpenv config-rm xdebug.ini || true

install:
  - |
      if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then
        travis_retry composer update --prefer-dist --no-interaction --ignore-platform-reqs
      else
        travis_retry composer update --prefer-dist --no-interaction
      fi

script:
    - $TEST_COMMAND --testsuite $SUITE
